#cloud-config

package_update: true
package_upgrade: true
packages:
  - nginx

write_files:
  - path: /usr/share/nginx/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to My Website</title>
      </head>
      <body>
          <h1>Hello, World!</h1>
          <p>This is a custom HTML page served from my Nginx server on EC2.</p>
      </body>
      </html>
    owner: root:root
    permissions: '0644'

runcmd:
  - systemctl enable nginx.service
  - systemctl restart nginx.service
